#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mnomre del nuevo usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mcontraseña para el usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32musuario valido por cuantos dias $name deve durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mlimite de logeos para el mismo usuario:\033[0;37m"; read -p " " limiteuser
	echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name ya existente\033[0m"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		( echo "$pass";echo "$pass" ) | passwd $name 2> /dev/null
		limite $name $limiteuser
		echo -e "\033[1;36mUsuario: \033[0m$name"
		echo -e "\033[1;36mSenha: \033[0m$pass"
		echo -e "\033[1;36mExpira:\033[0m $datexp"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	echo -e "Ou execute o criarusuario como sudo. \033[1;31msudo criarusuario\033[0m"
	else
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi
