#!/bin/bash
read -p "nombre del usuario a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer no existe"
 exit
 fi
clear
echo -e "\033[1;33mO que desea redefinir ?\033[1;30m
1) Numero de logins
2) fecha de expiracion
3) cambiar contraseña del usuario"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "cual es el nuevo limite de logeos: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "cual es la nueva fecha establecer : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "cual es el nuevo usuario para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "nueva contraseña aplicada"
exit
fi
